version: '3.5'
services:
  db:
    container_name: postgres
    image: postgres:9.6
    volumes:
      - pg-data:/var/lib/postgresql/data

  api:
    container_name: api
    build: .
    env_file: dev-env
    command: ["sleep", "9999"]
    ports:
      - 8000:8000
    volumes:
      - .:/smi-slave
    depends_on:
      - db

volumes:
  pg-data: {}
