version: '3.2'
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=smi-slave-dev
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  slave-api:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/smi-slave
    depends_on:
      - postgres
    environment: 
      - FLASK_ENV="docker"
      - FLASK_DEBUG=1
      - FLASK_APP=/smi-slave/src/app.py
    command: flask run
